name: jokrey_utilities
description: Utility algorithm in flutter. Some of these algorithms and utilities might exist in a similar form in other repositories in other languages. Notably this package currently contains a wrapper around the already quite good flutter-webrtc package. Encapsulates some complicated network signaling stuff and provides a websocket wrapper to communicate with a generic go signaling server (found in another repository).
version: 0.0.3
author: jokrey
homepage: https://github.com/jokrey

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  effective_dart: ^1.0.0

  #most important
  flutter_webrtc:
    git:
      url: git://github.com/flutter-webrtc/flutter-webrtc.git
      # the commit that fixed https://github.com/flutter-webrtc/flutter-webrtc/issues/437
      # Required to observe from browser
      ref: 61d473e4f53bb2164d9f5a905744fa9208028d59
  http: ^0.12.2
  web_socket_channel: ^1.1.0

  #ui
  date_time_picker: ^1.1.1
  flutter_countdown_timer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
